# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  gcg = {
    pname = "gcg";
    version = "v370";
    src = fetchFromGitHub {
      owner = "scipopt";
      repo = "gcg";
      rev = "v370";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = true;
      sha256 = "sha256-s0RlfwAVTaSS9FvLuyZvEcTI+UzJkNqh3THeNumS3bY=";
    };
  };
  ipopt = {
    pname = "ipopt";
    version = "releases/3.14.17";
    src = fetchFromGitHub {
      owner = "coin-or";
      repo = "Ipopt";
      rev = "releases/3.14.17";
      fetchSubmodules = false;
      sha256 = "sha256-0IRHryADQArhhtfbQjCy+EDvVRi/ywc51IwiQOfWlR4=";
    };
  };
  mip-dd = {
    pname = "mip-dd";
    version = "v2.0.0";
    src = fetchFromGitHub {
      owner = "scipopt";
      repo = "MIP-DD";
      rev = "v2.0.0";
      fetchSubmodules = false;
      sha256 = "sha256-r46ICeXUjFGKdGC+kBHEjGdA9nUjb7rkAmtOxYml0K4=";
    };
  };
  mumps-harness = {
    pname = "mumps-harness";
    version = "releases/3.0.9";
    src = fetchFromGitHub {
      owner = "coin-or-tools";
      repo = "ThirdParty-Mumps";
      rev = "releases/3.0.9";
      fetchSubmodules = false;
      sha256 = "sha256-WDveYhQzExQ445pcw/+6r8XMSx9KsBiYZzt5pkiWYO0=";
    };
  };
  papilo = {
    pname = "papilo";
    version = "v2.4.0";
    src = fetchFromGitHub {
      owner = "scipopt";
      repo = "papilo";
      rev = "v2.4.0";
      fetchSubmodules = false;
      sha256 = "sha256-WMw9v57nuP6MHj9Ft4l5FxdIF5VUWCRm/909tbz7VD4=";
    };
  };
  pygcgopt = {
    pname = "pygcgopt";
    version = "0e12361612473234a3115671ad8ae3cbdc649380";
    src = fetchFromGitHub {
      owner = "scipopt";
      repo = "PyGCGOpt";
      rev = "0e12361612473234a3115671ad8ae3cbdc649380";
      fetchSubmodules = false;
      sha256 = "sha256-rIaT1Pm3sENcxb9QOSWFXrXX0+sB/+GnXLoqKz73nYk=";
    };
    date = "2024-12-08";
  };
  pyscipopt = {
    pname = "pyscipopt";
    version = "v5.2.1";
    src = fetchFromGitHub {
      owner = "scipopt";
      repo = "PySCIPOpt";
      rev = "v5.2.1";
      fetchSubmodules = false;
      sha256 = "sha256-dGXv1hvxPqeRWQz3Iy9ByoRy2GYoDJmW9CmdXpXanfQ=";
    };
  };
  pysoplex = {
    pname = "pysoplex";
    version = "0def0a370ea08d1f1f34b0e5a2e03f7e5881ac9c";
    src = fetchFromGitHub {
      owner = "scipopt";
      repo = "PySoPlex";
      rev = "0def0a370ea08d1f1f34b0e5a2e03f7e5881ac9c";
      fetchSubmodules = false;
      sha256 = "sha256-8/bndwQ0aUSMl3XTZctfW3SH85IIrlCln6+9cQGuU9Q=";
    };
    date = "2024-02-27";
  };
  scip = {
    pname = "scip";
    version = "v920";
    src = fetchFromGitHub {
      owner = "scipopt";
      repo = "scip";
      rev = "v920";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = true;
      sha256 = "sha256-JCk1T74apNDNiSBQL3gGFi6EgC7qV75rDXCTDSZkEKw=";
    };
  };
  scippp = {
    pname = "scippp";
    version = "1.2.0";
    src = fetchFromGitHub {
      owner = "scipopt";
      repo = "SCIPpp";
      rev = "1.2.0";
      fetchSubmodules = false;
      sha256 = "sha256-RbxIgATECLJCopShm98+ogfFoCv2yWH1/1QcZyo9GKo=";
    };
  };
  soplex = {
    pname = "soplex";
    version = "release-712";
    src = fetchFromGitHub {
      owner = "scipopt";
      repo = "soplex";
      rev = "release-712";
      fetchSubmodules = true;
      deepClone = false;
      leaveDotGit = true;
      sha256 = "sha256-d2PhwfW46wcQGiMXfL3hzyZP50i2xoH7ZdC1WoC4/JE=";
    };
  };
  vipr = {
    pname = "vipr";
    version = "d499c7c5e832f00d28ae1da9d0aa3b4877f3233f";
    src = fetchFromGitHub {
      owner = "scipopt";
      repo = "vipr";
      rev = "d499c7c5e832f00d28ae1da9d0aa3b4877f3233f";
      fetchSubmodules = false;
      sha256 = "sha256-ggeyeEQIy12IqP3l8vv77toOD3XNNlF1tuG63Wirizk=";
    };
    date = "2025-01-07";
  };
  zimpl = {
    pname = "zimpl";
    version = "v362";
    src = fetchFromGitHub {
      owner = "scipopt";
      repo = "zimpl";
      rev = "v362";
      fetchSubmodules = false;
      sha256 = "sha256-juqAwzqBArsFXmz7L7RQaE78EhQdP5P51wQFlCoo7/o=";
    };
  };
}
