# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  gcg = {
    pname = "gcg";
    version = "v363";
    src = fetchFromGitHub {
      owner = "scipopt";
      repo = "gcg";
      rev = "v363";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = true;
      sha256 = "sha256-ese9nR9mWorYBDxFcQGdk6LNIRM/FhuvGI3QyC6cQmM=";
    };
  };
  ipopt = {
    pname = "ipopt";
    version = "releases/3.14.16";
    src = fetchFromGitHub {
      owner = "coin-or";
      repo = "Ipopt";
      rev = "releases/3.14.16";
      fetchSubmodules = false;
      sha256 = "sha256-ZuiZZMq7NzOm6CCJgMBgEWs8PEfM3pVr2yOWbS42l8U=";
    };
  };
  mip-dd = {
    pname = "mip-dd";
    version = "v2.0.0";
    src = fetchFromGitHub {
      owner = "scipopt";
      repo = "MIP-DD";
      rev = "v2.0.0";
      fetchSubmodules = false;
      sha256 = "sha256-r46ICeXUjFGKdGC+kBHEjGdA9nUjb7rkAmtOxYml0K4=";
    };
  };
  mumps-harness = {
    pname = "mumps-harness";
    version = "releases/3.0.8";
    src = fetchFromGitHub {
      owner = "coin-or-tools";
      repo = "ThirdParty-Mumps";
      rev = "releases/3.0.8";
      fetchSubmodules = false;
      sha256 = "sha256-z42cNy+IlFRXAbtfPsyL3Z6kjVAJYfic/m4IaG2smn8=";
    };
  };
  papilo = {
    pname = "papilo";
    version = "v2.3.1";
    src = fetchFromGitHub {
      owner = "scipopt";
      repo = "papilo";
      rev = "v2.3.1";
      fetchSubmodules = false;
      sha256 = "sha256-N7ToON8Jx9zq4TKYVElxTn1aNDd5WiaHXPPVxF1CQpM=";
    };
  };
  pygcgopt = {
    pname = "pygcgopt";
    version = "f8e6393218185c02f6dbf68352f781086cdd310a";
    src = fetchFromGitHub {
      owner = "scipopt";
      repo = "PyGCGOpt";
      rev = "f8e6393218185c02f6dbf68352f781086cdd310a";
      fetchSubmodules = false;
      sha256 = "sha256-1duHmPs9chAWEMdXb+pWhDXUjb2z4fh9RZSpmiI7H4s=";
    };
    date = "2024-10-10";
  };
  pyscipopt = {
    pname = "pyscipopt";
    version = "v5.1.1";
    src = fetchFromGitHub {
      owner = "scipopt";
      repo = "PySCIPOpt";
      rev = "v5.1.1";
      fetchSubmodules = false;
      sha256 = "sha256-j51AxMG1DPD/ORqkEzoBncpPnciqBaQBmOE7PnzakwA=";
    };
  };
  pysoplex = {
    pname = "pysoplex";
    version = "0def0a370ea08d1f1f34b0e5a2e03f7e5881ac9c";
    src = fetchFromGitHub {
      owner = "scipopt";
      repo = "PySoPlex";
      rev = "0def0a370ea08d1f1f34b0e5a2e03f7e5881ac9c";
      fetchSubmodules = false;
      sha256 = "sha256-8/bndwQ0aUSMl3XTZctfW3SH85IIrlCln6+9cQGuU9Q=";
    };
    date = "2024-02-27";
  };
  scip = {
    pname = "scip";
    version = "v911";
    src = fetchFromGitHub {
      owner = "scipopt";
      repo = "scip";
      rev = "v911";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = true;
      sha256 = "sha256-eNbXbmoU1DCF810kIPcH5jOFkSa/5+IHHOyI9K96jZM=";
    };
  };
  scippp = {
    pname = "scippp";
    version = "1.2.0";
    src = fetchFromGitHub {
      owner = "scipopt";
      repo = "SCIPpp";
      rev = "1.2.0";
      fetchSubmodules = false;
      sha256 = "sha256-RbxIgATECLJCopShm98+ogfFoCv2yWH1/1QcZyo9GKo=";
    };
  };
  soplex = {
    pname = "soplex";
    version = "release-711";
    src = fetchFromGitHub {
      owner = "scipopt";
      repo = "soplex";
      rev = "release-711";
      fetchSubmodules = true;
      deepClone = false;
      leaveDotGit = true;
      sha256 = "sha256-eozfQttKyrG3Qc3zcHsuuxxvvGzNaQHLTFbfEsR7GuQ=";
    };
  };
  vipr = {
    pname = "vipr";
    version = "c83f4c208d6f4f9dd2ec372065701c93e0d5522b";
    src = fetchFromGitHub {
      owner = "scipopt";
      repo = "vipr";
      rev = "c83f4c208d6f4f9dd2ec372065701c93e0d5522b";
      fetchSubmodules = false;
      sha256 = "sha256-iaz/QD7kj/2g/DonuNCf1aJn/8mD/JseOgElAza4W+8=";
    };
    date = "2024-10-23";
  };
  zimpl = {
    pname = "zimpl";
    version = "v362";
    src = fetchFromGitHub {
      owner = "scipopt";
      repo = "zimpl";
      rev = "v362";
      fetchSubmodules = false;
      sha256 = "sha256-juqAwzqBArsFXmz7L7RQaE78EhQdP5P51wQFlCoo7/o=";
    };
  };
}
